__author__ = 'Regend'

SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://qa:Qa123456@private-qa.mysql.rds.aliyuncs.com:3306/pjmsg?charset=utf8'
SQLALCHEMY_POOL_SIZE = 20
SQLALCHEMY_MAX_OVERFLOW = 5
SQLALCHEMY_COMMIT_TEARDOWN = True
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_COMMIT_ON_TEARDOWN = True
SQLALCHEMY_ECHO = True
